platform :ios, '9.0'

target 'TodoIz' do
 
  use_frameworks!

  # Pods for TodoIz

pod 'RealmSwift'
pod 'SwipeCellKit'

pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
